# Generated by Django 4.1.3 on 2023-01-18 16:57

from django.db import migrations, models
import user_face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=user_face.models.user_directory_path)),
                ('face_encoding', models.TextField()),
            ],
        ),
    ]
